Repository SSR3-FinalPj/frontend_SOS, pull requests merged in 2025-08, with the labels that each got.

#15 refactor: 대시보드 컴포넌트 분리 및 번역 시스템 최적화
  .gitignore
  src/components/LandingInteractive.jsx
  src/components/dashboard/analytics_filter_sidebar.jsx
  src/components/dashboard/dashboard_header.jsx
  src/components/dashboard/detailed_analytics_view.jsx
  src/components/dashboard/enhanced-platform-card.jsx
  src/components/dashboard/glass_card.jsx
  src/components/dashboard/main_dashboard_view.jsx
  src/components/dashboard/settings_view.jsx
  src/components/dashboard/sidebar.jsx
  src/components/login/LoginCard.jsx
  src/constants/dashboard_constants.js
  src/hooks/use_analytics_filters.js
  src/hooks/use_dashboard_data.jsx
  src/pages/Dashboard.jsx
  src/pages/LoginPage.jsx
  src/stores/dashboard_store.js
  src/utils/dashboard_utils.js
Labels: refactor

#25 chore: Move favicon to public directory
  index.html
  public/Favicon/favicon.svg
Labels: refactor

#27 #16 브랜치의 내용을 병합
  src/components/ui/accordion.jsx
  src/components/ui/alert-dialog.jsx
  src/components/ui/alert.jsx
  src/components/ui/aspect-ratio.jsx
  src/components/ui/avatar.jsx
  src/components/ui/breadcrumb.jsx
  src/components/ui/checkbox.jsx
  src/components/ui/context-menu.jsx
  src/components/ui/drawer.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/form.jsx
  src/components/ui/hover-card.jsx
  src/components/ui/input-otp.jsx
  src/components/ui/label.jsx
  src/components/ui/menubar.jsx
  src/components/ui/navigation-menu.jsx
  src/components/ui/popover.jsx
  src/components/ui/progress.jsx
  src/components/ui/radio-group.jsx
  src/components/ui/resizable.jsx
  src/components/ui/scroll-area.jsx
  src/components/ui/select.jsx
  src/components/ui/sidebar.jsx
  src/components/ui/slider.jsx
  src/components/ui/sonner.jsx
  src/components/ui/switch.jsx
  src/components/ui/table.jsx
  src/components/ui/tabs.jsx
  src/components/ui/toggle-group.jsx
  src/components/ui/toggle.jsx
Labels: refactor

#42 feat: AI 미디어 제작 요청 기능 추가 및 컴포넌트 리팩토링
  src/components/dashboard/ai_media_request_modal.jsx
  src/components/dashboard/content_launch_view.jsx
  src/components/ui/button.jsx
  src/components/ui/category_accordion.jsx
  src/components/ui/image_uploader.jsx
  src/components/ui/location_selector.jsx
  src/components/ui/success_modal.jsx
  src/hooks/use_media_request_form.js
  src/utils/location_data.js
  src/utils/media_request_constants.js
Labels: enhancement

#55 🚀 PR: 랜딩 페이지 기능 구현 및 UX 개선
  .gitignore
  App.jsx
  src/components/common/CookieConsentBanner.jsx
  src/components/common/GlassFeatureCard.jsx
  src/components/common/InfoModal.jsx
  src/components/common/Section.jsx
  src/components/landing/FeaturesSection.jsx
  src/components/landing/Footer.jsx
  src/components/landing/ReadySection.jsx
  src/components/landing/TransformSection.jsx
  src/constants/legalTexts.js
  src/pages/LandingPage.jsx
Labels: ✨ feat, ♻️ refactor

#62 SSE 전역 아키텍처 및 Premium 알림 시스템
  App.jsx
  src/components/common/SSEProvider.jsx
  src/components/dashboard/content_launch_view.jsx
  src/components/ui/notification.jsx
  src/hooks/useAccessTokenMemory.js
  src/hooks/use_sse_connection.js
  src/lib/token.js
  src/stores/notification_store.js
Labels: ✨ feat, ♻️ refactor

#65 feat(UX): 실시간 알림 시스템 고도화 및 콘텐츠 론치 자동화
  src/components/dashboard/ai_media_request_modal.jsx
  src/components/dashboard/content_item_card.jsx
  src/components/dashboard/content_launch_view.jsx
  src/components/dashboard/content_preview_modal.jsx
  src/components/ui/notification.jsx
  src/hooks/use_content_launch.jsx
  src/hooks/use_media_request_form.js
  src/hooks/use_sse_connection.js
  src/stores/notification_store.js
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#66 분석페이지 그래프 위치와 최신 콘텐츠 업로드 부분 목데이터 > api 연동하였습니다.
  src/components/dashboard/UploadedContentList.jsx
  src/components/dashboard/connection-management-card.jsx
  src/components/dashboard/content-list-view.jsx
  src/components/dashboard/dashboard_header.jsx
  src/components/dashboard/data-export-card.jsx
  src/components/dashboard/detailed_analytics_view.jsx
  src/components/dashboard/enhanced-platform-card.jsx
  src/components/dashboard/glass_card.jsx
  src/components/ui/AudienceDemographicsChart.jsx
  src/components/ui/TrafficSourceChart.jsx
  src/components/ui/glass-card.jsx
  src/lib/token.js
  src/stores/analytics_store.js
  src/utils/dashboard_constants.js
  src/utils/dashboard_utils.js
Labels: ✨ feat, 🐛 fix

#74 AI 콘텐츠 론칭 기능 안정화 및 개선
  App.jsx
  src/components/common/SSEProvider.jsx
  src/components/common/VideoAnalysisModal.jsx
  src/components/dashboard/UploadedContentList.jsx
  src/components/dashboard/content-list-view.jsx
  src/components/dashboard/content_folder_card.jsx
  src/components/dashboard/content_item_card.jsx
  src/components/dashboard/content_launch_view.jsx
  src/components/dashboard/content_preview_modal.jsx
  src/components/dashboard/content_publish_modal.jsx
  src/components/dashboard/data-export-card.jsx
  src/components/dashboard/detailed_analytics_view.jsx
  src/components/dashboard/websocket_provider.jsx
  src/components/ui/notification.jsx
  src/hooks/usePlatformInitializer.js
  src/hooks/useYouTubeChannelInfo.js
  src/hooks/use_content_launch.jsx
  src/hooks/use_media_request_form.js
  src/hooks/use_mobile.js
  src/hooks/use_sse_connection.js
  src/hooks/use_websocket.js
  src/lib/api.js
  src/pages/AnalyticsPage.jsx
  src/stores/notification_store.js
  src/stores/page_store.js
Labels: ✨ feat, 🐛 fix, ♻️ refactor, 🎨 style

#77 AI 생성 영상 기능 구현 및 안정성 개선
  src/components/dashboard/VideoStreamTestPanel.jsx
  src/components/dashboard/content_item_card.jsx
  src/components/dashboard/content_launch_view.jsx
  src/components/dashboard/generated_video_preview_modal.jsx
  src/components/ui/natural_prompt_input.jsx
  src/hooks/use_content_launch.jsx
  src/hooks/use_media_request_form.js
  src/lib/api.js
  src/pages/ContentLaunchPage.jsx
Labels: ✨ feat, 🐛 fix, ♻️ refactor
